### ISSUE TITLE
프로젝트 상세 페이지 total member 다르게 나옴

### ISSUE THREAD

**Issue by seoysauce** [42DoProject/DoProject#507]
![스크린샷 2021-11-18 오전 1 24 21](https://user-images.githubusercontent.com/65898861/142240077-7d05371a-556c-467a-8727-d45427c23f55.png)

- 프로젝트에 멤버가 가입한 후 수정을 눌러 빈 포지션을 삭제했을 때 발생

total member가 2명인데 1명으로 나옵니다
- 프로젝트 수정 페이지에서는 빈 포지션을 position: [0, 1, 1] 과 같은 형태로 POST해주고
- 프로젝트 상세 페이지에서는 currentMember / totalMember 로 데이터를 표시합니다.

**Comment by Daewoong-Jeon** [comment]
updateList API에서 잘못계산하고 있는 것 같습니다. 수정해서 pr 올릴게용
