### ISSUE TITLE
[front] member가 많으면 튀어나갑니다

### ISSUE THREAD

**Issue by seoysauce** [42DoProject/DoProject#556]
![스크린샷 2021-11-21 오후 7 02 09](https://user-images.githubusercontent.com/65898861/142757625-d4c085eb-b467-4429-b6e0-7179d972b79a.png)

flex-wrap: wrap 처리 해주셔야 되는데
filled-member 랑 empty-member? 가 따로 되어있어서 제가 처리가 어렵습니다.

**Comment by seuyu42** [comment]
수정완료했습니다~
