### ISSUE TITLE
[front] 프로젝트 댓글 pagination 마지막 페이지 활성화

### ISSUE THREAD

**Issue by seoysauce** [42DoProject/DoProject#563]
댓글이 5개를 넘길 경우 가장 최신에 달린 댓글이 다음 페이지로 넘어가 묻히게 됩니다.

- pagination에서 첫페이지가 아닌 가장 마지막 페이지를 기본으로 보여주어야 할 것 같습니다.
- 댓글 5개는 너무 짧은 것 같습니다.
 (최소 10개~15개 정도로 늘려주세요)

**Comment by seuyu42** [comment]
수정완료 했습니다~
