### ISSUE TITLE
[back] 라운지 댓글 알림 시 댓글이 10자이내일 경우 "..." 붙지 않게 수정

### ISSUE THREAD

**Issue by seoysauce** [42DoProject/DoProject#624]
<img width="337" alt="스크린샷 2021-11-26 오후 6 10 25" src="https://user-images.githubusercontent.com/65898861/143555962-e7756c69-1367-4097-88d4-9bc6574e68db.png">

back에서 알림 데이터를 보내줄 때 앞의 10자까지 자르고 + "..."를 붙여주는데
"ㅎㅇㅇ" <- 등과 같이 10자보다 짧은경우는 "..."를 붙여줄 필요가 없을 것 같습니다.

**Comment by Daewoong-Jeon** [comment]
넵 알겠습니다
