### ISSUE TITLE
[front] 프로젝트 저장 및 삭제 버튼

### ISSUE THREAD

**Issue by Daewoong-Jeon** [42DoProject/DoProject#651]
- 프로젝트 저장 및 삭제 버튼의 위치가 불편할 수도 있다는 생각이 듭니다.
보통 저장버튼이 왼쪽, 삭제 버튼이 오른쪽에 위치하는 것으로 알고있는데,
수정이 필요 없는 것 같다면 이슈 삭제하겠습니다!
![스크린샷 2021-11-30 오전 1 22 25](https://user-images.githubusercontent.com/59330163/143904585-5a5d9074-9690-446d-9335-938888d741c8.png)

**Comment by seoysauce** [comment]
수정했습니다!
